import Foundation
import GRDB

public enum AttributionWriter {
    public static func markdown(for snapshotURL: URL) throws -> String {
        let snapshot = try KnowledgeSnapshot.open(at: snapshotURL)
        let meta = try snapshot.meta()
        let rows = try snapshot.database.writer.read { db in
            try Row.fetchAll(
                db,
                sql: """
                    SELECT record_id, citation FROM knowledge_attribution
                    ORDER BY record_id, citation
                    """
            )
        }
        var lines: [String] = []
        lines.append("# Knowledge snapshot attribution")
        lines.append("")
        lines.append("Generated by the knowledge importer. Do not edit by hand.")
        lines.append("")
        if let version = meta["snapshot_version"] {
            lines.append("Snapshot version: `\(version)`")
            lines.append("")
        }
        lines.append(contentsOf: sourceLines(meta))
        lines.append(contentsOf: try imageLines(snapshot))
        lines.append("## Record citations")
        lines.append("")
        var currentRecord = ""
        for row in rows {
            let record: String = row["record_id"]
            let citation: String = row["citation"]
            if record != currentRecord {
                if !currentRecord.isEmpty {
                    lines.append("")
                }
                lines.append("### \(record)")
                lines.append("")
                currentRecord = record
            }
            lines.append("- \(citation)")
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private static func sourceLines(_ meta: [String: String]) -> [String] {
        let provenanceKeys = meta.keys
            .filter { $0.hasPrefix("input_provenance:") }
            .sorted()
        guard !provenanceKeys.isEmpty else { return [] }
        var lines = ["## Sources", ""]
        for key in provenanceKeys {
            let name = key.replacingOccurrences(of: "input_provenance:", with: "")
            lines.append("- **\(name)**: \(meta[key] ?? "")")
        }
        lines.append("")
        return lines
    }

    private static func imageLines(_ snapshot: KnowledgeSnapshot) throws -> [String] {
        let rows = try snapshot.database.writer.read { db -> [Row] in
            guard try db.tableExists("knowledge_image") else { return [] }
            return try Row.fetchAll(
                db,
                sql: """
                    SELECT file, license, license_url, artist, source_page_url
                    FROM knowledge_image
                    ORDER BY owner_kind, owner_id, kind, file
                    """
            )
        }
        guard !rows.isEmpty else { return [] }
        var lines = ["## Images", ""]
        for row in rows {
            let file: String = row["file"]
            let license: String = row["license"]
            let page: String = row["source_page_url"]
            let artist: String? = row["artist"]
            let licenseURL: String? = row["license_url"]
            let licenseText = licenseURL.map { "[\(license)](\($0))" } ?? license
            var parts = ["`\(file)`", "[source](\(page))", licenseText]
            if let artist {
                parts.append(artist)
            }
            lines.append("- " + parts.joined(separator: " · "))
        }
        lines.append("")
        return lines
    }
}
