import Foundation
import GRDB

public enum AttributionWriter {
    public static func markdown(for snapshotURL: URL) throws -> String {
        let snapshot = try KnowledgeSnapshot.open(at: snapshotURL)
        let meta = try snapshot.meta()
        let rows = try snapshot.database.writer.read { db in
            try Row.fetchAll(
                db,
                sql: """
                    SELECT record_id, citation FROM knowledge_attribution
                    ORDER BY record_id, citation
                    """
            )
        }
        var lines: [String] = []
        lines.append("# Knowledge snapshot attribution")
        lines.append("")
        lines.append("Generated by the knowledge importer. Do not edit by hand.")
        lines.append("")
        if let version = meta["snapshot_version"] {
            lines.append("Snapshot version: `\(version)`")
            lines.append("")
        }
        let provenanceKeys = meta.keys
            .filter { $0.hasPrefix("input_provenance:") }
            .sorted()
        if !provenanceKeys.isEmpty {
            lines.append("## Sources")
            lines.append("")
            for key in provenanceKeys {
                let name = key.replacingOccurrences(of: "input_provenance:", with: "")
                lines.append("- **\(name)**: \(meta[key] ?? "")")
            }
            lines.append("")
        }
        lines.append("## Record citations")
        lines.append("")
        var currentRecord = ""
        for row in rows {
            let record: String = row["record_id"]
            let citation: String = row["citation"]
            if record != currentRecord {
                if !currentRecord.isEmpty {
                    lines.append("")
                }
                lines.append("### \(record)")
                lines.append("")
                currentRecord = record
            }
            lines.append("- \(citation)")
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }
}
